# Welcome to Ultimate Jekyll!
# This is the default configuration file for your project.

# Project
url: "https://webtrafficbot.com"
baseurl: ""

# Theme
theme:
  id: "classy"
  target: "frontend"
  appearance: "dark"
  version: "latest"
  html:
    class: ""
  body:
    class: ""
  nav:
    enabled: true
  main:
    class: ""
  footer:
    enabled: true

# Meta
meta:
  title: "Traffic Bot - Unlimited free website traffic generator - {{ site.brand.name }}"
  description: "Free web traffic bot for Mac, Windows & Linux. Lower your site's bounce rate & rank higher on search engines with our traffic generator. Generate unlimited traffic for free"
  image: "https://cdn.itwcreativeworks.com/assets/somiibo/images/socials/somiibo-brandmark-square-blue-1024x1024.png"
  keywords: ""
  viewport: ""
  index: true
  referrer: ""

# Brand
brand:
  id: ""
  name: "Web Traffic Bot"
  description: "Unlimited free website traffic generator"
  type: "Corporation"
  images:
    brandmark: "https://cdn.itwcreativeworks.com/assets/somiibo/images/logo/somiibo-brandmark-blue-1024x1024.png"
    wordmark: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-wordmark-black-x.svg"
    combomark: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-combomark-black-x.svg"
  contact:
    email: "support@somiibo.com"
    phone: "+1 (000) 000 - 0000"
    slapform-form-id: "000000"
  address:
    line1: "4001 Inglewood Ave"
    line2: "Suite 101-385"
    region: "CA"
    postal-code: "90278"
    city: "Redondo Beach"
    locality: "Los Angeles"
    country: "United States"

# Web Manager
web_manager:
  auth:
    enabled: true
    config:
      policy: null
      redirects:
        authenticated: "/account"
        unauthenticated: "/signup"
      allowSubdomains: true
  firebase:
    app:
      enabled: true
      config:
        apiKey: "AIzaSyA3-YBkywbzpstijvMqUwn_a0GQTi3EZQc"
        authDomain: "somiibo.com"
        databaseURL: "https://somiibo-91d13.firebaseio.com"
        projectId: "somiibo-91d13"
        storageBucket: "somiibo-91d13.appspot.com"
        messagingSenderId: "605660972329"
        appId: "1:605660972329:web:4860b3b7afb8591f"
        measurementId: "G-PM3ZKCHLMS"
    appCheck:
      enabled: false
      config:
        siteKey: "6LddIDsoAAAAAIlymzmJuwr9Ktz7vS7e0LLxY4kd"
  cookieConsent:
    enabled: true
    config:
      palette:
        popup:
          background: "#1fb7f2"
          text: "#fff"
        button:
          background: "#fff"
          text: "#1fb7f2"
  chatsy:
    enabled: true
    config:
      accountId: "98WVIFYdGrUbjL4jgyXLPe8ICFt1"
      chatId: "NcEywcnfLMs1cB"
      settings:
        openChatButton:
          background: "#1fb7f2"
          text: "#fff"
  sentry:
    enabled: true
    config:
      dsn: ""
      release: "ultimate-jekyll-website"
      replaysSessionSampleRate: 0.01
      replaysOnErrorSampleRate: 0.01
  exitPopup:
    enabled: true
    config:
      timeout: 1000 * 60 * 60 * 4
      title: "Special Offer!"
      message: "Get 15% off your purchase of our Premium plans."
      okButton:
        text: "Claim 15% Discount"
        link: "/pricing"
  lazyLoading:
    enabled: true
    config:
      rootMargin: "50px 0px"
      threshold: 0.01
  socialSharing:
    enabled: false
    config:
      defaultPlatforms: ["facebook", "twitter", "linkedin", "pinterest", "reddit", "email", "copy"]
      buttonClass: ""
      openInNewWindow: true
  pushNotifications:
    enabled: true
    config:
      autoRequest: 1000 * 60
  validRedirectHosts: []

# Socials
socials:
  facebook: null
  twitter: null
  linkedin: null
  youtube: null
  instagram: null
  tumblr: null
  slack: null
  discord: null
  github: null
  dev: null
  tiktok: null
  twitch: null
  soundcloud: null
  spotify: null
  mixcloud: null

# Tracking
tracking:
  google-analytics: "G-QGQX1TLWZC"
  meta-pixel: null
  tiktok-pixel: null

# Favicon
favicon:
  path: "https://cdn.itwcreativeworks.com/assets/somiibo/images/favicon"
  safari-pinned-tab: "#5bbad5"
  msapp-tile-color: "#da532c"
  theme-color: "#ffffff"

# Cloudflare
cloudflare:
  zone: "44df437b80ddd43477258ecbc5dbfed5"

# Download
download:
  mac:
    universal: ""
  windows:
    universal: ""
  linux:
    debian: ""
    snap: ""
  ios:
    universal: ""
  android:
    universal: ""

# Extension
extension:
  chrome: ""
  firefox: ""
  opera: ""
  safari: ""
  edge: ""

# Manifest
manifest:
  name: "Web Traffic Bot"
  short-name: "Web Traffic Bot"
  theme-color: "#ffffff"
  background-color: "#ffffff"
  display: "standalone"
  start-url: "/?source=pwa"
  scope: "/"
  orientation: "portrait"

# Translation
translation:
  enabled: false
  default: "en"
  languages:
    - "zh"
    - "es"
    - "hi"
    - "ar"
    - "pt"
    - "ru"
    - "ja"
    - "de"
    - "fr"
    - "ko"
    - "ur"
    - "id"
    - "bn"
    - "tl"
    - "vi"
    - "it"

# Icons
icons:
  style: "solid"

# Blog & Pagination
permalink: /blog/:title
pagination:
  enabled: true
  per_page: 6
  offset: 0
  limit: 0
  permalink: /page/:num.html
  title: :title - page :num
  sort_field: date
  sort_reverse: true

# Jekyll collections
collections:
  team:
    title: Team Members
    output: true

# Jekyll defaults
defaults:
- scope:
    path: ""
    type: team
  values:
    permalink: /team/:title
